### ISSUE TITLE
remove top toolbar and introduce slide out menu

### ISSUE THREAD

**Issue by ahmednosman** [cartologic/cartoview_geonode_viewer#11]
group all tools and functions into two location
- slide out menu
   (logo) - new add to config
    <Map Title>
    - About
    - layers
    - legend
    - Query
    - Measure
    - chart
    - time 
    - Print
    
- Toolbar on map
    - zoom and pan tools
    - 3D view

**Comment by hishamkaram** [comment]
@Amira-Mohiey  please close this issue with your commit url
